ps2keybd-obj-i586   = $(patsubst %.c, %.o, $(wildcard $(MODULE_DIR)/ps2keybd/*.c))
ps2keybd-obj-i586  += $(patsubst %.s, %.o, $(wildcard $(MODULE_DIR)/ps2keybd/*.s))
ps2keybd-link-i586 += $(MODOBJ_DIR)/ps2keybd_mod.o

mod-obj-y += $(ps2keybd-obj-$(ARCH)) $(ps2keybd-link-$(ARCH))

$(MODOBJ_DIR)/ps2keybd_mod.o: $(ps2keybd-obj-$(ARCH))
	@$(LD) $(MOD_LDFLAGS) -o $@ $(ps2keybd-obj-$(ARCH))
	@echo "[ ] LD $(MOD_LDFLAGS) -o $@ *.o"
