vga-obj-y   = $(patsubst %.c, %.o, $(wildcard $(MODULE_DIR)/vga/*.c))
vga-obj-y  += $(patsubst %.s, %.o, $(wildcard $(MODULE_DIR)/vga/*.s))
vga-link-y += $(MODOBJ_DIR)/vga_mod.o

mod-obj-y += $(vga-obj-y) $(vga-link-y)

$(MODOBJ_DIR)/vga_mod.o: $(vga-obj-y)
	@$(LD) $(MOD_LDFLAGS) -o $@ $(vga-obj-y)
	@echo "[ ] LD $(MOD_LDFLAGS) -o $@ *.o"
