cppmod-obj-y   = $(patsubst %.c, %.o, $(wildcard $(MODULE_DIR)/cppmod/*.c))
cppmod-obj-y   = $(patsubst %.cpp, %.o, $(wildcard $(MODULE_DIR)/cppmod/*.cpp))
cppmod-obj-y  += $(patsubst %.s, %.o, $(wildcard $(MODULE_DIR)/cppmod/*.s))
cppmod-link-y += $(MODOBJ_DIR)/cppmod_mod.o

mod-obj-y += $(cppmod-obj-y) $(cppmod-link-y)

$(MODOBJ_DIR)/cppmod_mod.o: $(cppmod-obj-y)
	@$(LD) $(MOD_LDFLAGS) -o $@ $(cppmod-obj-y)
	@echo "[ ] LD $(MOD_LDFLAGS) -o $@ *.o"
